version: "3"
services:
  backend-ssg:
    container_name: backend-ssg
    image: node:18
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command:
      ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    depends_on:
      - mongo-fourb
    environment:
      - VIRTUAL_HOST=fourb.localhost
      - MONGO_DB=mongodb://mongo-fourb:27017

  loadbalancer:
    image: jwilder/nginx-proxy
    depends_on:
      - backend-ssg
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./loadbalancer/custom.conf:/etc/nginx/conf.d/custom.conf
      - ./loadbalancer/certs:/etc/nginx/certs
      - ./loadbalancer/dhparam:/etc/nginx/dhparam
    logging:
      driver: none
    ports:
      - '443:443'

  mongo-fourb:
    container_name: mongo-fourb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: none
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all"]
